<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $cities = '[
            {"id":"1","province_id":"1","city_name_ar":"15 مايو","city_name_en":"15 May"},
            {"id":"2","province_id":"1","city_name_ar":"الازبكية","city_name_en":"Al Azbakeyah"},
            {"id":"3","province_id":"1","city_name_ar":"البساتين","city_name_en":"Al Basatin"},
            {"id":"4","province_id":"1","city_name_ar":"التبين","city_name_en":"Tebin"},
            {"id":"5","province_id":"1","city_name_ar":"الخليفة","city_name_en":"El-Khalifa"},
            {"id":"6","province_id":"1","city_name_ar":"الدراسة","city_name_en":"El darrasa"},
            {"id":"7","province_id":"1","city_name_ar":"الدرب الاحمر","city_name_en":"Aldarb Alahmar"},
            {"id":"8","province_id":"1","city_name_ar":"الزاوية الحمراء","city_name_en":"Zawya al-Hamra"},
            {"id":"9","province_id":"1","city_name_ar":"الزيتون","city_name_en":"El-Zaytoun"},
            {"id":"10","province_id":"1","city_name_ar":"الساحل","city_name_en":"Sahel"},
            {"id":"11","province_id":"1","city_name_ar":"السلام","city_name_en":"El Salam"},
            {"id":"12","province_id":"1","city_name_ar":"السيدة زينب","city_name_en":"Sayeda Zeinab"},
            {"id":"13","province_id":"1","city_name_ar":"الشرابية","city_name_en":"El Sharabeya"},
            {"id":"14","province_id":"1","city_name_ar":"مدينة الشروق","city_name_en":"Shorouk"},
            {"id":"15","province_id":"1","city_name_ar":"الظاهر","city_name_en":"El Daher"},
            {"id":"16","province_id":"1","city_name_ar":"العتبة","city_name_en":"Ataba"},
            {"id":"17","province_id":"1","city_name_ar":"القاهرة الجديدة","city_name_en":"New Cairo"},
            {"id":"18","province_id":"1","city_name_ar":"المرج","city_name_en":"El Marg"},
            {"id":"19","province_id":"1","city_name_ar":"عزبة النخل","city_name_en":"Ezbet el Nakhl"},
            {"id":"20","province_id":"1","city_name_ar":"المطرية","city_name_en":"Matareya"},
            {"id":"21","province_id":"1","city_name_ar":"المعادى","city_name_en":"Maadi"},
            {"id":"22","province_id":"1","city_name_ar":"المعصرة","city_name_en":"Maasara"},
            {"id":"23","province_id":"1","city_name_ar":"المقطم","city_name_en":"Mokattam"},
            {"id":"24","province_id":"1","city_name_ar":"المنيل","city_name_en":"Manyal"},
            {"id":"25","province_id":"1","city_name_ar":"الموسكى","city_name_en":"Mosky"},
            {"id":"26","province_id":"1","city_name_ar":"النزهة","city_name_en":"Nozha"},
            {"id":"27","province_id":"1","city_name_ar":"الوايلى","city_name_en":"Waily"},
            {"id":"28","province_id":"1","city_name_ar":"باب الشعرية","city_name_en":"Bab al-Shereia"},
            {"id":"29","province_id":"1","city_name_ar":"بولاق","city_name_en":"Bolaq"},
            {"id":"30","province_id":"1","city_name_ar":"جاردن سيتى","city_name_en":"Garden City"},
            {"id":"31","province_id":"1","city_name_ar":"حدائق القبة","city_name_en":"Hadayek El-Kobba"},
            {"id":"32","province_id":"1","city_name_ar":"حلوان","city_name_en":"Helwan"},
            {"id":"33","province_id":"1","city_name_ar":"دار السلام","city_name_en":"Dar Al Salam"},
            {"id":"34","province_id":"1","city_name_ar":"شبرا","city_name_en":"Shubra"},
            {"id":"35","province_id":"1","city_name_ar":"طره","city_name_en":"Tura"},
            {"id":"36","province_id":"1","city_name_ar":"عابدين","city_name_en":"Abdeen"},
            {"id":"37","province_id":"1","city_name_ar":"عباسية","city_name_en":"Abaseya"},
            {"id":"38","province_id":"1","city_name_ar":"عين شمس","city_name_en":"Ain Shams"},
            {"id":"39","province_id":"1","city_name_ar":"مدينة نصر","city_name_en":"Nasr City"},
            {"id":"40","province_id":"1","city_name_ar":"مصر الجديدة","city_name_en":"New Heliopolis"},
            {"id":"41","province_id":"1","city_name_ar":"مصر القديمة","city_name_en":"Masr Al Qadima"},
            {"id":"42","province_id":"1","city_name_ar":"منشية ناصر","city_name_en":"Mansheya Nasir"},
            {"id":"43","province_id":"1","city_name_ar":"مدينة بدر","city_name_en":"Badr City"},
            {"id":"44","province_id":"1","city_name_ar":"مدينة العبور","city_name_en":"Obour City"},
            {"id":"45","province_id":"1","city_name_ar":"وسط البلد","city_name_en":"Cairo Downtown"},
            {"id":"46","province_id":"1","city_name_ar":"الزمالك","city_name_en":"Zamalek"},
            {"id":"47","province_id":"1","city_name_ar":"قصر النيل","city_name_en":"Kasr El Nile"},
            {"id":"48","province_id":"1","city_name_ar":"الرحاب","city_name_en":"Rehab"},
            {"id":"49","province_id":"1","city_name_ar":"القطامية","city_name_en":"Katameya"},
            {"id":"50","province_id":"1","city_name_ar":"مدينتي","city_name_en":"Madinty"},
            {"id":"51","province_id":"1","city_name_ar":"روض الفرج","city_name_en":"Rod Alfarag"},
            {"id":"52","province_id":"1","city_name_ar":"شيراتون","city_name_en":"Sheraton"},
            {"id":"53","province_id":"1","city_name_ar":"الجمالية","city_name_en":"El-Gamaleya"},
            {"id":"54","province_id":"1","city_name_ar":"العاشر من رمضان","city_name_en":"10th of Ramadan City"},
            {"id":"55","province_id":"1","city_name_ar":"الحلمية","city_name_en":"Helmeyat Alzaytoun"},
            {"id":"56","province_id":"1","city_name_ar":"النزهة الجديدة","city_name_en":"New Nozha"},
            {"id":"57","province_id":"1","city_name_ar":"العاصمة الإدارية","city_name_en":"Capital New"},
            {"id":"58","province_id":"2","city_name_ar":"الجيزة","city_name_en":"Giza"},
            {"id":"59","province_id":"2","city_name_ar":"السادس من أكتوبر","city_name_en":"Sixth of October"},
            {"id":"60","province_id":"2","city_name_ar":"الشيخ زايد","city_name_en":"Cheikh Zayed"},
            {"id":"61","province_id":"2","city_name_ar":"الحوامدية","city_name_en":"Hawamdiyah"},
            {"id":"62","province_id":"2","city_name_ar":"البدرشين","city_name_en":"Al Badrasheen"},
            {"id":"63","province_id":"2","city_name_ar":"الصف","city_name_en":"Saf"},
            {"id":"64","province_id":"2","city_name_ar":"أطفيح","city_name_en":"Atfih"},
            {"id":"65","province_id":"2","city_name_ar":"العياط","city_name_en":"Al Ayat"},
            {"id":"66","province_id":"2","city_name_ar":"الباويطي","city_name_en":"Al-Bawaiti"},
            {"id":"67","province_id":"2","city_name_ar":"منشأة القناطر","city_name_en":"ManshiyetAl Qanater"},
            {"id":"68","province_id":"2","city_name_ar":"أوسيم","city_name_en":"Oaseem"},
            {"id":"69","province_id":"2","city_name_ar":"كرداسة","city_name_en":"Kerdasa"},
            {"id":"70","province_id":"2","city_name_ar":"أبو النمرس","city_name_en":"Abu Nomros"},
            {"id":"71","province_id":"2","city_name_ar":"كفر غطاطي","city_name_en":"Kafr Ghati"},
            {"id":"72","province_id":"2","city_name_ar":"منشأة البكاري","city_name_en":"Manshiyet Al Bakari"},
            {"id":"73","province_id":"2","city_name_ar":"الدقى","city_name_en":"Dokki"},
            {"id":"74","province_id":"2","city_name_ar":"العجوزة","city_name_en":"Agouza"},
            {"id":"75","province_id":"2","city_name_ar":"الهرم","city_name_en":"Haram"},
            {"id":"76","province_id":"2","city_name_ar":"الوراق","city_name_en":"Warraq"},
            {"id":"77","province_id":"2","city_name_ar":"امبابة","city_name_en":"Imbaba"},
            {"id":"78","province_id":"2","city_name_ar":"بولاق الدكرور","city_name_en":"Boulaq Dakrour"},
            {"id":"79","province_id":"2","city_name_ar":"الواحات البحرية","city_name_en":"Al Wahat Al Baharia"},
            {"id":"80","province_id":"2","city_name_ar":"العمرانية","city_name_en":"Omraneya"},
            {"id":"81","province_id":"2","city_name_ar":"المنيب","city_name_en":"Moneeb"},
            {"id":"82","province_id":"2","city_name_ar":"بين السرايات","city_name_en":"Bin Alsarayat"},
            {"id":"83","province_id":"2","city_name_ar":"الكيت كات","city_name_en":"Kit Kat"},
            {"id":"84","province_id":"2","city_name_ar":"المهندسين","city_name_en":"Mohandessin"},
            {"id":"85","province_id":"2","city_name_ar":"فيصل","city_name_en":"Faisal"},
            {"id":"86","province_id":"2","city_name_ar":"أبو رواش","city_name_en":"Abu Rawash"},
            {"id":"87","province_id":"2","city_name_ar":"حدائق الأهرام","city_name_en":"Hadayek Alahram"},
            {"id":"88","province_id":"2","city_name_ar":"الحرانية","city_name_en":"Haraneya"},
            {"id":"89","province_id":"2","city_name_ar":"حدائق اكتوبر","city_name_en":"Hadayek October"},
            {"id":"90","province_id":"2","city_name_ar":"صفط اللبن","city_name_en":"Saft Allaban"},
            {"id":"91","province_id":"2","city_name_ar":"القرية الذكية","city_name_en":"Smart Village"},
            {"id":"92","province_id":"2","city_name_ar":"ارض اللواء","city_name_en":"Ard Ellwaa"},
            {"id":"93","province_id":"3","city_name_ar":"ابو قير","city_name_en":"Abu Qir"},
            {"id":"94","province_id":"3","city_name_ar":"الابراهيمية","city_name_en":"Al Ibrahimeyah"},
            {"id":"95","province_id":"3","city_name_ar":"الأزاريطة","city_name_en":"Azarita"},
            {"id":"96","province_id":"3","city_name_ar":"الانفوشى","city_name_en":"Anfoushi"},
            {"id":"97","province_id":"3","city_name_ar":"الدخيلة","city_name_en":"Dekheila"},
            {"id":"98","province_id":"3","city_name_ar":"السيوف","city_name_en":"El Soyof"},
            {"id":"99","province_id":"3","city_name_ar":"العامرية","city_name_en":"Ameria"},
            {"id":"100","province_id":"3","city_name_ar":"اللبان","city_name_en":"El Labban"},
            {"id":"101","province_id":"3","city_name_ar":"المفروزة","city_name_en":"Al Mafrouza"},
            {"id":"102","province_id":"3","city_name_ar":"المنتزه","city_name_en":"El Montaza"},
            {"id":"103","province_id":"3","city_name_ar":"المنشية","city_name_en":"Mansheya"},
            {"id":"104","province_id":"3","city_name_ar":"الناصرية","city_name_en":"Naseria"},
            {"id":"105","province_id":"3","city_name_ar":"امبروزو","city_name_en":"Ambrozo"},
            {"id":"106","province_id":"3","city_name_ar":"باب شرق","city_name_en":"Bab Sharq"},
            {"id":"107","province_id":"3","city_name_ar":"برج العرب","city_name_en":"Bourj Alarab"},
            {"id":"108","province_id":"3","city_name_ar":"ستانلى","city_name_en":"Stanley"},
            {"id":"109","province_id":"3","city_name_ar":"سموحة","city_name_en":"Smouha"},
            {"id":"110","province_id":"3","city_name_ar":"سيدى بشر","city_name_en":"Sidi Bishr"},
            {"id":"111","province_id":"3","city_name_ar":"شدس","city_name_en":"Shads"},
            {"id":"112","province_id":"3","city_name_ar":"غيط العنب","city_name_en":"Gheet Alenab"},
            {"id":"113","province_id":"3","city_name_ar":"فلمينج","city_name_en":"Fleming"},
            {"id":"114","province_id":"3","city_name_ar":"فيكتوريا","city_name_en":"Victoria"},
            {"id":"115","province_id":"3","city_name_ar":"كامب شيزار","city_name_en":"Camp Shizar"},
            {"id":"116","province_id":"3","city_name_ar":"كرموز","city_name_en":"Karmooz"},
            {"id":"117","province_id":"3","city_name_ar":"محطة الرمل","city_name_en":"Mahta Alraml"},
            {"id":"118","province_id":"3","city_name_ar":"مينا البصل","city_name_en":"Mina El-Basal"},
            {"id":"119","province_id":"3","city_name_ar":"العصافرة","city_name_en":"Asafra"},
            {"id":"120","province_id":"3","city_name_ar":"العجمي","city_name_en":"Agamy"},
            {"id":"121","province_id":"3","city_name_ar":"بكوس","city_name_en":"Bakos"},
            {"id":"122","province_id":"3","city_name_ar":"بولكلي","city_name_en":"Boulkly"},
            {"id":"123","province_id":"3","city_name_ar":"كليوباترا","city_name_en":"Cleopatra"},
            {"id":"124","province_id":"3","city_name_ar":"جليم","city_name_en":"Glim"},
            {"id":"125","province_id":"3","city_name_ar":"المعمورة","city_name_en":"Al Mamurah"},
            {"id":"126","province_id":"3","city_name_ar":"المندرة","city_name_en":"Al Mandara"},
            {"id":"127","province_id":"3","city_name_ar":"محرم بك","city_name_en":"Moharam Bek"},
            {"id":"128","province_id":"3","city_name_ar":"الشاطبي","city_name_en":"Elshatby"},
            {"id":"129","province_id":"3","city_name_ar":"سيدي جابر","city_name_en":"Sidi Gaber"},
            {"id":"130","province_id":"3","city_name_ar":"الساحل الشمالي","city_name_en":"North Coast\/sahel"},
            {"id":"131","province_id":"3","city_name_ar":"الحضرة","city_name_en":"Alhadra"},
            {"id":"132","province_id":"3","city_name_ar":"العطارين","city_name_en":"Alattarin"},
            {"id":"133","province_id":"3","city_name_ar":"سيدي كرير","city_name_en":"Sidi Kerir"},
            {"id":"134","province_id":"3","city_name_ar":"الجمرك","city_name_en":"Elgomrok"},
            {"id":"135","province_id":"3","city_name_ar":"المكس","city_name_en":"Al Max"},
            {"id":"136","province_id":"3","city_name_ar":"مارينا","city_name_en":"Marina"},
            {"id":"137","province_id":"4","city_name_ar":"المنصورة","city_name_en":"Mansoura"},
            {"id":"138","province_id":"4","city_name_ar":"طلخا","city_name_en":"Talkha"},
            {"id":"139","province_id":"4","city_name_ar":"ميت غمر","city_name_en":"Mitt Ghamr"},
            {"id":"140","province_id":"4","city_name_ar":"دكرنس","city_name_en":"Dekernes"},
            {"id":"141","province_id":"4","city_name_ar":"أجا","city_name_en":"Aga"},
            {"id":"142","province_id":"4","city_name_ar":"منية النصر","city_name_en":"Menia El Nasr"},
            {"id":"143","province_id":"4","city_name_ar":"السنبلاوين","city_name_en":"Sinbillawin"},
            {"id":"144","province_id":"4","city_name_ar":"الكردي","city_name_en":"El Kurdi"},
            {"id":"145","province_id":"4","city_name_ar":"بني عبيد","city_name_en":"Bani Ubaid"},
            {"id":"146","province_id":"4","city_name_ar":"المنزلة","city_name_en":"Al Manzala"},
            {"id":"147","province_id":"4","city_name_ar":"تمي الأمديد","city_name_en":"tami al\'amdid"},
            {"id":"148","province_id":"4","city_name_ar":"الجمالية","city_name_en":"aljamalia"},
            {"id":"149","province_id":"4","city_name_ar":"شربين","city_name_en":"Sherbin"},
            {"id":"150","province_id":"4","city_name_ar":"المطرية","city_name_en":"Mataria"},
            {"id":"151","province_id":"4","city_name_ar":"بلقاس","city_name_en":"Belqas"},
            {"id":"152","province_id":"4","city_name_ar":"ميت سلسيل","city_name_en":"Meet Salsil"},
            {"id":"153","province_id":"4","city_name_ar":"جمصة","city_name_en":"Gamasa"},
            {"id":"154","province_id":"4","city_name_ar":"محلة دمنة","city_name_en":"Mahalat Damana"},
            {"id":"155","province_id":"4","city_name_ar":"نبروه","city_name_en":"Nabroh"},
            {"id":"156","province_id":"5","city_name_ar":"الغردقة","city_name_en":"Hurghada"},
            {"id":"157","province_id":"5","city_name_ar":"رأس غارب","city_name_en":"Ras Ghareb"},
            {"id":"158","province_id":"5","city_name_ar":"سفاجا","city_name_en":"Safaga"},
            {"id":"159","province_id":"5","city_name_ar":"القصير","city_name_en":"El Qusiar"},
            {"id":"160","province_id":"5","city_name_ar":"مرسى علم","city_name_en":"Marsa Alam"},
            {"id":"161","province_id":"5","city_name_ar":"الشلاتين","city_name_en":"Shalatin"},
            {"id":"162","province_id":"5","city_name_ar":"حلايب","city_name_en":"Halaib"},
            {"id":"163","province_id":"5","city_name_ar":"الدهار","city_name_en":"Aldahar"},
            {"id":"164","province_id":"6","city_name_ar":"دمنهور","city_name_en":"Damanhour"},
            {"id":"165","province_id":"6","city_name_ar":"كفر الدوار","city_name_en":"Kafr El Dawar"},
            {"id":"166","province_id":"6","city_name_ar":"رشيد","city_name_en":"Rashid"},
            {"id":"167","province_id":"6","city_name_ar":"إدكو","city_name_en":"Edco"},
            {"id":"168","province_id":"6","city_name_ar":"أبو المطامير","city_name_en":"Abu al-Matamir"},
            {"id":"169","province_id":"6","city_name_ar":"أبو حمص","city_name_en":"Abu Homs"},
            {"id":"170","province_id":"6","city_name_ar":"الدلنجات","city_name_en":"Delengat"},
            {"id":"171","province_id":"6","city_name_ar":"المحمودية","city_name_en":"Mahmoudiyah"},
            {"id":"172","province_id":"6","city_name_ar":"الرحمانية","city_name_en":"Rahmaniyah"},
            {"id":"173","province_id":"6","city_name_ar":"إيتاي البارود","city_name_en":"Itai Baroud"},
            {"id":"174","province_id":"6","city_name_ar":"حوش عيسى","city_name_en":"Housh Eissa"},
            {"id":"175","province_id":"6","city_name_ar":"شبراخيت","city_name_en":"Shubrakhit"},
            {"id":"176","province_id":"6","city_name_ar":"كوم حمادة","city_name_en":"Kom Hamada"},
            {"id":"177","province_id":"6","city_name_ar":"بدر","city_name_en":"Badr"},
            {"id":"178","province_id":"6","city_name_ar":"وادي النطرون","city_name_en":"Wadi Natrun"},
            {"id":"179","province_id":"6","city_name_ar":"النوبارية الجديدة","city_name_en":"New Nubaria"},
            {"id":"180","province_id":"6","city_name_ar":"النوبارية","city_name_en":"Alnoubareya"},
            {"id":"181","province_id":"7","city_name_ar":"الفيوم","city_name_en":"Fayoum"},
            {"id":"182","province_id":"7","city_name_ar":"الفيوم الجديدة","city_name_en":"Fayoum El Gedida"},
            {"id":"183","province_id":"7","city_name_ar":"طامية","city_name_en":"Tamiya"},
            {"id":"184","province_id":"7","city_name_ar":"سنورس","city_name_en":"Snores"},
            {"id":"185","province_id":"7","city_name_ar":"إطسا","city_name_en":"Etsa"},
            {"id":"186","province_id":"7","city_name_ar":"إبشواي","city_name_en":"Epschway"},
            {"id":"187","province_id":"7","city_name_ar":"يوسف الصديق","city_name_en":"Yusuf El Sediaq"},
            {"id":"188","province_id":"7","city_name_ar":"الحادقة","city_name_en":"Hadqa"},
            {"id":"189","province_id":"7","city_name_ar":"اطسا","city_name_en":"Atsa"},
            {"id":"190","province_id":"7","city_name_ar":"الجامعة","city_name_en":"Algamaa"},
            {"id":"191","province_id":"7","city_name_ar":"السيالة","city_name_en":"Sayala"},
            {"id":"192","province_id":"8","city_name_ar":"طنطا","city_name_en":"Tanta"},
            {"id":"193","province_id":"8","city_name_ar":"المحلة الكبرى","city_name_en":"Al Mahalla Al Kobra"},
            {"id":"194","province_id":"8","city_name_ar":"كفر الزيات","city_name_en":"Kafr El Zayat"},
            {"id":"195","province_id":"8","city_name_ar":"زفتى","city_name_en":"Zefta"},
            {"id":"196","province_id":"8","city_name_ar":"السنطة","city_name_en":"El Santa"},
            {"id":"197","province_id":"8","city_name_ar":"قطور","city_name_en":"Qutour"},
            {"id":"198","province_id":"8","city_name_ar":"بسيون","city_name_en":"Basion"},
            {"id":"199","province_id":"8","city_name_ar":"سمنود","city_name_en":"Samannoud"},
            {"id":"200","province_id":"9","city_name_ar":"الإسماعيلية","city_name_en":"Ismailia"},
            {"id":"201","province_id":"9","city_name_ar":"فايد","city_name_en":"Fayed"},
            {"id":"202","province_id":"9","city_name_ar":"القنطرة شرق","city_name_en":"Qantara Sharq"},
            {"id":"203","province_id":"9","city_name_ar":"القنطرة غرب","city_name_en":"Qantara Gharb"},
            {"id":"204","province_id":"9","city_name_ar":"التل الكبير","city_name_en":"El Tal El Kabier"},
            {"id":"205","province_id":"9","city_name_ar":"أبو صوير","city_name_en":"Abu Sawir"},
            {"id":"206","province_id":"9","city_name_ar":"القصاصين الجديدة","city_name_en":"Kasasien El Gedida"},
            {"id":"207","province_id":"9","city_name_ar":"نفيشة","city_name_en":"Nefesha"},
            {"id":"208","province_id":"9","city_name_ar":"الشيخ زايد","city_name_en":"Sheikh Zayed"},
            {"id":"209","province_id":"10","city_name_ar":"شبين الكوم","city_name_en":"Shbeen El Koom"},
            {"id":"210","province_id":"10","city_name_ar":"مدينة السادات","city_name_en":"Sadat City"},
            {"id":"211","province_id":"10","city_name_ar":"منوف","city_name_en":"Menouf"},
            {"id":"212","province_id":"10","city_name_ar":"سرس الليان","city_name_en":"Sars El-Layan"},
            {"id":"213","province_id":"10","city_name_ar":"أشمون","city_name_en":"Ashmon"},
            {"id":"214","province_id":"10","city_name_ar":"الباجور","city_name_en":"Al Bagor"},
            {"id":"215","province_id":"10","city_name_ar":"قويسنا","city_name_en":"Quesna"},
            {"id":"216","province_id":"10","city_name_ar":"بركة السبع","city_name_en":"Berkat El Saba"},
            {"id":"217","province_id":"10","city_name_ar":"تلا","city_name_en":"Tala"},
            {"id":"218","province_id":"10","city_name_ar":"الشهداء","city_name_en":"Al Shohada"},
            {"id":"219","province_id":"11","city_name_ar":"المنيا","city_name_en":"Minya"},
            {"id":"220","province_id":"11","city_name_ar":"المنيا الجديدة","city_name_en":"Minya El Gedida"},
            {"id":"221","province_id":"11","city_name_ar":"العدوة","city_name_en":"El Adwa"},
            {"id":"222","province_id":"11","city_name_ar":"مغاغة","city_name_en":"Magagha"},
            {"id":"223","province_id":"11","city_name_ar":"بني مزار","city_name_en":"Bani Mazar"},
            {"id":"224","province_id":"11","city_name_ar":"مطاي","city_name_en":"Mattay"},
            {"id":"225","province_id":"11","city_name_ar":"سمالوط","city_name_en":"Samalut"},
            {"id":"226","province_id":"11","city_name_ar":"المدينة الفكرية","city_name_en":"Madinat El Fekria"},
            {"id":"227","province_id":"11","city_name_ar":"ملوي","city_name_en":"Meloy"},
            {"id":"228","province_id":"11","city_name_ar":"دير مواس","city_name_en":"Deir Mawas"},
            {"id":"229","province_id":"11","city_name_ar":"ابو قرقاص","city_name_en":"Abu Qurqas"},
            {"id":"230","province_id":"11","city_name_ar":"ارض سلطان","city_name_en":"Ard Sultan"},
            {"id":"231","province_id":"12","city_name_ar":"بنها","city_name_en":"Banha"},
            {"id":"232","province_id":"12","city_name_ar":"قليوب","city_name_en":"Qalyub"},
            {"id":"233","province_id":"12","city_name_ar":"شبرا الخيمة","city_name_en":"Shubra Al Khaimah"},
            {"id":"234","province_id":"12","city_name_ar":"القناطر الخيرية","city_name_en":"Al Qanater Charity"},
            {"id":"235","province_id":"12","city_name_ar":"الخانكة","city_name_en":"Khanka"},
            {"id":"236","province_id":"12","city_name_ar":"كفر شكر","city_name_en":"Kafr Shukr"},
            {"id":"237","province_id":"12","city_name_ar":"طوخ","city_name_en":"Tukh"},
            {"id":"238","province_id":"12","city_name_ar":"قها","city_name_en":"Qaha"},
            {"id":"239","province_id":"12","city_name_ar":"العبور","city_name_en":"Obour"},
            {"id":"240","province_id":"12","city_name_ar":"الخصوص","city_name_en":"Khosous"},
            {"id":"241","province_id":"12","city_name_ar":"شبين القناطر","city_name_en":"Shibin Al Qanater"},
            {"id":"242","province_id":"12","city_name_ar":"مسطرد","city_name_en":"Mostorod"},
            {"id":"243","province_id":"13","city_name_ar":"الخارجة","city_name_en":"El Kharga"},
            {"id":"244","province_id":"13","city_name_ar":"باريس","city_name_en":"Paris"},
            {"id":"245","province_id":"13","city_name_ar":"موط","city_name_en":"Mout"},
            {"id":"246","province_id":"13","city_name_ar":"الفرافرة","city_name_en":"Farafra"},
            {"id":"247","province_id":"13","city_name_ar":"بلاط","city_name_en":"Balat"},
            {"id":"248","province_id":"13","city_name_ar":"الداخلة","city_name_en":"Dakhla"},
            {"id":"249","province_id":"14","city_name_ar":"السويس","city_name_en":"Suez"},
            {"id":"250","province_id":"14","city_name_ar":"الجناين","city_name_en":"Alganayen"},
            {"id":"251","province_id":"14","city_name_ar":"عتاقة","city_name_en":"Ataqah"},
            {"id":"252","province_id":"14","city_name_ar":"العين السخنة","city_name_en":"Ain Sokhna"},
            {"id":"253","province_id":"14","city_name_ar":"فيصل","city_name_en":"Faysal"},
            {"id":"254","province_id":"15","city_name_ar":"أسوان","city_name_en":"Aswan"},
            {"id":"255","province_id":"15","city_name_ar":"أسوان الجديدة","city_name_en":"Aswan El Gedida"},
            {"id":"256","province_id":"15","city_name_ar":"دراو","city_name_en":"Drau"},
            {"id":"257","province_id":"15","city_name_ar":"كوم أمبو","city_name_en":"Kom Ombo"},
            {"id":"258","province_id":"15","city_name_ar":"نصر النوبة","city_name_en":"Nasr Al Nuba"},
            {"id":"259","province_id":"15","city_name_ar":"كلابشة","city_name_en":"Kalabsha"},
            {"id":"260","province_id":"15","city_name_ar":"إدفو","city_name_en":"Edfu"},
            {"id":"261","province_id":"15","city_name_ar":"الرديسية","city_name_en":"Al-Radisiyah"},
            {"id":"262","province_id":"15","city_name_ar":"البصيلية","city_name_en":"Al Basilia"},
            {"id":"263","province_id":"15","city_name_ar":"السباعية","city_name_en":"Al Sibaeia"},
            {"id":"264","province_id":"15","city_name_ar":"ابوسمبل السياحية","city_name_en":"Abo Simbl Al Siyahia"},
            {"id":"265","province_id":"15","city_name_ar":"مرسى علم","city_name_en":"Marsa Alam"},
            {"id":"266","province_id":"16","city_name_ar":"أسيوط","city_name_en":"Assiut"},
            {"id":"267","province_id":"16","city_name_ar":"أسيوط الجديدة","city_name_en":"Assiut El Gedida"},
            {"id":"268","province_id":"16","city_name_ar":"ديروط","city_name_en":"Dayrout"},
            {"id":"269","province_id":"16","city_name_ar":"منفلوط","city_name_en":"Manfalut"},
            {"id":"270","province_id":"16","city_name_ar":"القوصية","city_name_en":"Qusiya"},
            {"id":"271","province_id":"16","city_name_ar":"أبنوب","city_name_en":"Abnoub"},
            {"id":"272","province_id":"16","city_name_ar":"أبو تيج","city_name_en":"Abu Tig"},
            {"id":"273","province_id":"16","city_name_ar":"الغنايم","city_name_en":"El Ghanaim"},
            {"id":"274","province_id":"16","city_name_ar":"ساحل سليم","city_name_en":"Sahel Selim"},
            {"id":"275","province_id":"16","city_name_ar":"البداري","city_name_en":"El Badari"},
            {"id":"276","province_id":"16","city_name_ar":"صدفا","city_name_en":"Sidfa"},
            {"id":"277","province_id":"17","city_name_ar":"بني سويف","city_name_en":"Bani Sweif"},
            {"id":"278","province_id":"17","city_name_ar":"بني سويف الجديدة","city_name_en":"Beni Suef El Gedida"},
            {"id":"279","province_id":"17","city_name_ar":"الواسطى","city_name_en":"Al Wasta"},
            {"id":"280","province_id":"17","city_name_ar":"ناصر","city_name_en":"Naser"},
            {"id":"281","province_id":"17","city_name_ar":"إهناسيا","city_name_en":"Ehnasia"},
            {"id":"282","province_id":"17","city_name_ar":"ببا","city_name_en":"beba"},
            {"id":"283","province_id":"17","city_name_ar":"الفشن","city_name_en":"Fashn"},
            {"id":"284","province_id":"17","city_name_ar":"سمسطا","city_name_en":"Somasta"},
            {"id":"285","province_id":"17","city_name_ar":"الاباصيرى","city_name_en":"Alabbaseri"},
            {"id":"286","province_id":"17","city_name_ar":"مقبل","city_name_en":"Mokbel"},
            {"id":"287","province_id":"18","city_name_ar":"بورسعيد","city_name_en":"PorSaid"},
            {"id":"288","province_id":"18","city_name_ar":"بورفؤاد","city_name_en":"Port Fouad"},
            {"id":"289","province_id":"18","city_name_ar":"العرب","city_name_en":"Alarab"},
            {"id":"290","province_id":"18","city_name_ar":"حى الزهور","city_name_en":"Zohour"},
            {"id":"291","province_id":"18","city_name_ar":"حى الشرق","city_name_en":"Alsharq"},
            {"id":"292","province_id":"18","city_name_ar":"حى الضواحى","city_name_en":"Aldawahi"},
            {"id":"293","province_id":"18","city_name_ar":"حى المناخ","city_name_en":"Almanakh"},
            {"id":"294","province_id":"18","city_name_ar":"حى مبارك","city_name_en":"Mubarak"},
            {"id":"295","province_id":"19","city_name_ar":"دمياط","city_name_en":"Damietta"},
            {"id":"296","province_id":"19","city_name_ar":"دمياط الجديدة","city_name_en":"New Damietta"},
            {"id":"297","province_id":"19","city_name_ar":"رأس البر","city_name_en":"Ras El Bar"},
            {"id":"298","province_id":"19","city_name_ar":"فارسكور","city_name_en":"Faraskour"},
            {"id":"299","province_id":"19","city_name_ar":"الزرقا","city_name_en":"Zarqa"},
            {"id":"300","province_id":"19","city_name_ar":"السرو","city_name_en":"alsaru"},
            {"id":"301","province_id":"19","city_name_ar":"الروضة","city_name_en":"alruwda"},
            {"id":"302","province_id":"19","city_name_ar":"كفر البطيخ","city_name_en":"Kafr El-Batikh"},
            {"id":"303","province_id":"19","city_name_ar":"عزبة البرج","city_name_en":"Azbet Al Burg"},
            {"id":"304","province_id":"19","city_name_ar":"ميت أبو غالب","city_name_en":"Meet Abou Ghalib"},
            {"id":"305","province_id":"19","city_name_ar":"كفر سعد","city_name_en":"Kafr Saad"},
            {"id":"306","province_id":"20","city_name_ar":"الزقازيق","city_name_en":"Zagazig"},
            {"id":"307","province_id":"20","city_name_ar":"العاشر من رمضان","city_name_en":"Al Ashr Men Ramadan"},
            {"id":"308","province_id":"20","city_name_ar":"منيا القمح","city_name_en":"Minya Al Qamh"},
            {"id":"309","province_id":"20","city_name_ar":"بلبيس","city_name_en":"Belbeis"},
            {"id":"310","province_id":"20","city_name_ar":"مشتول السوق","city_name_en":"Mashtoul El Souq"},
            {"id":"311","province_id":"20","city_name_ar":"القنايات","city_name_en":"Qenaiat"},
            {"id":"312","province_id":"20","city_name_ar":"أبو حماد","city_name_en":"Abu Hammad"},
            {"id":"313","province_id":"20","city_name_ar":"القرين","city_name_en":"El Qurain"},
            {"id":"314","province_id":"20","city_name_ar":"ههيا","city_name_en":"Hehia"},
            {"id":"315","province_id":"20","city_name_ar":"أبو كبير","city_name_en":"Abu Kabir"},
            {"id":"316","province_id":"20","city_name_ar":"فاقوس","city_name_en":"Faccus"},
            {"id":"317","province_id":"20","city_name_ar":"الصالحية الجديدة","city_name_en":"El Salihia El Gedida"},
            {"id":"318","province_id":"20","city_name_ar":"الإبراهيمية","city_name_en":"Al Ibrahimiyah"},
            {"id":"319","province_id":"20","city_name_ar":"ديرب نجم","city_name_en":"Deirb Negm"},
            {"id":"320","province_id":"20","city_name_ar":"كفر صقر","city_name_en":"Kafr Saqr"},
            {"id":"321","province_id":"20","city_name_ar":"أولاد صقر","city_name_en":"Awlad Saqr"},
            {"id":"322","province_id":"20","city_name_ar":"الحسينية","city_name_en":"Husseiniya"},
            {"id":"323","province_id":"20","city_name_ar":"صان الحجر القبلية","city_name_en":"san alhajar alqablia"},
            {"id":"324","province_id":"20","city_name_ar":"منشأة أبو عمر","city_name_en":"Manshayat Abu Omar"},
            {"id":"325","province_id":"21","city_name_ar":"الطور","city_name_en":"Al Toor"},
            {"id":"326","province_id":"21","city_name_ar":"شرم الشيخ","city_name_en":"Sharm El-Shaikh"},
            {"id":"327","province_id":"21","city_name_ar":"دهب","city_name_en":"Dahab"},
            {"id":"328","province_id":"21","city_name_ar":"نويبع","city_name_en":"Nuweiba"},
            {"id":"329","province_id":"21","city_name_ar":"طابا","city_name_en":"Taba"},
            {"id":"330","province_id":"21","city_name_ar":"سانت كاترين","city_name_en":"Saint Catherine"},
            {"id":"331","province_id":"21","city_name_ar":"أبو رديس","city_name_en":"Abu Redis"},
            {"id":"332","province_id":"21","city_name_ar":"أبو زنيمة","city_name_en":"Abu Zenaima"},
            {"id":"333","province_id":"21","city_name_ar":"رأس سدر","city_name_en":"Ras Sidr"},
            {"id":"334","province_id":"22","city_name_ar":"كفر الشيخ","city_name_en":"Kafr El Sheikh"},
            {"id":"335","province_id":"22","city_name_ar":"وسط البلد كفر الشيخ","city_name_en":"Kafr El Sheikh Downtown"},
            {"id":"336","province_id":"22","city_name_ar":"دسوق","city_name_en":"Desouq"},
            {"id":"337","province_id":"22","city_name_ar":"فوه","city_name_en":"Fooh"},
            {"id":"338","province_id":"22","city_name_ar":"مطوبس","city_name_en":"Metobas"},
            {"id":"339","province_id":"22","city_name_ar":"برج البرلس","city_name_en":"Burg Al Burullus"},
            {"id":"340","province_id":"22","city_name_ar":"بلطيم","city_name_en":"Baltim"},
            {"id":"341","province_id":"22","city_name_ar":"مصيف بلطيم","city_name_en":"Masief Baltim"},
            {"id":"342","province_id":"22","city_name_ar":"الحامول","city_name_en":"Hamol"},
            {"id":"343","province_id":"22","city_name_ar":"بيلا","city_name_en":"Bella"},
            {"id":"344","province_id":"22","city_name_ar":"الرياض","city_name_en":"Riyadh"},
            {"id":"345","province_id":"22","city_name_ar":"سيدي سالم","city_name_en":"Sidi Salm"},
            {"id":"346","province_id":"22","city_name_ar":"قلين","city_name_en":"Qellen"},
            {"id":"347","province_id":"22","city_name_ar":"سيدي غازي","city_name_en":"Sidi Ghazi"},
            {"id":"348","province_id":"23","city_name_ar":"مرسى مطروح","city_name_en":"Marsa Matrouh"},
            {"id":"349","province_id":"23","city_name_ar":"الحمام","city_name_en":"El Hamam"},
            {"id":"350","province_id":"23","city_name_ar":"العلمين","city_name_en":"Alamein"},
            {"id":"351","province_id":"23","city_name_ar":"الضبعة","city_name_en":"Dabaa"},
            {"id":"352","province_id":"23","city_name_ar":"النجيلة","city_name_en":"Al-Nagila"},
            {"id":"353","province_id":"23","city_name_ar":"سيدي براني","city_name_en":"Sidi Brani"},
            {"id":"354","province_id":"23","city_name_ar":"السلوم","city_name_en":"Salloum"},
            {"id":"355","province_id":"23","city_name_ar":"سيوة","city_name_en":"Siwa"},
            {"id":"356","province_id":"23","city_name_ar":"مارينا","city_name_en":"Marina"},
            {"id":"357","province_id":"23","city_name_ar":"الساحل الشمالى","city_name_en":"North Coast"},
            {"id":"358","province_id":"24","city_name_ar":"الأقصر","city_name_en":"Luxor"},
            {"id":"359","province_id":"24","city_name_ar":"الأقصر الجديدة","city_name_en":"New Luxor"},
            {"id":"360","province_id":"24","city_name_ar":"إسنا","city_name_en":"Esna"},
            {"id":"361","province_id":"24","city_name_ar":"طيبة الجديدة","city_name_en":"New Tiba"},
            {"id":"362","province_id":"24","city_name_ar":"الزينية","city_name_en":"Al ziynia"},
            {"id":"363","province_id":"24","city_name_ar":"البياضية","city_name_en":"Al Bayadieh"},
            {"id":"364","province_id":"24","city_name_ar":"القرنة","city_name_en":"Al Qarna"},
            {"id":"365","province_id":"24","city_name_ar":"أرمنت","city_name_en":"Armant"},
            {"id":"366","province_id":"24","city_name_ar":"الطود","city_name_en":"Al Tud"},
            {"id":"367","province_id":"25","city_name_ar":"قنا","city_name_en":"Qena"},
            {"id":"368","province_id":"25","city_name_ar":"قنا الجديدة","city_name_en":"New Qena"},
            {"id":"369","province_id":"25","city_name_ar":"ابو طشت","city_name_en":"Abu Tesht"},
            {"id":"370","province_id":"25","city_name_ar":"نجع حمادي","city_name_en":"Nag Hammadi"},
            {"id":"371","province_id":"25","city_name_ar":"دشنا","city_name_en":"Deshna"},
            {"id":"372","province_id":"25","city_name_ar":"الوقف","city_name_en":"Alwaqf"},
            {"id":"373","province_id":"25","city_name_ar":"قفط","city_name_en":"Qaft"},
            {"id":"374","province_id":"25","city_name_ar":"نقادة","city_name_en":"Naqada"},
            {"id":"375","province_id":"25","city_name_ar":"فرشوط","city_name_en":"Farshout"},
            {"id":"376","province_id":"25","city_name_ar":"قوص","city_name_en":"Quos"},
            {"id":"377","province_id":"26","city_name_ar":"العريش","city_name_en":"Arish"},
            {"id":"378","province_id":"26","city_name_ar":"الشيخ زويد","city_name_en":"Sheikh Zowaid"},
            {"id":"379","province_id":"26","city_name_ar":"نخل","city_name_en":"Nakhl"},
            {"id":"380","province_id":"26","city_name_ar":"رفح","city_name_en":"Rafah"},
            {"id":"381","province_id":"26","city_name_ar":"بئر العبد","city_name_en":"Bir al-Abed"},
            {"id":"382","province_id":"26","city_name_ar":"الحسنة","city_name_en":"Al Hasana"},
            {"id":"383","province_id":"27","city_name_ar":"سوهاج","city_name_en":"Sohag"},
            {"id":"384","province_id":"27","city_name_ar":"سوهاج الجديدة","city_name_en":"Sohag El Gedida"},
            {"id":"385","province_id":"27","city_name_ar":"أخميم","city_name_en":"Akhmeem"},
            {"id":"386","province_id":"27","city_name_ar":"أخميم الجديدة","city_name_en":"Akhmim El Gedida"},
            {"id":"387","province_id":"27","city_name_ar":"البلينا","city_name_en":"Albalina"},
            {"id":"388","province_id":"27","city_name_ar":"المراغة","city_name_en":"El Maragha"},
            {"id":"389","province_id":"27","city_name_ar":"المنشأة","city_name_en":"almunsha\'a"},
            {"id":"390","province_id":"27","city_name_ar":"دار السلام","city_name_en":"Dar AISalaam"},
            {"id":"391","province_id":"27","city_name_ar":"جرجا","city_name_en":"Gerga"},
            {"id":"392","province_id":"27","city_name_ar":"جهينة الغربية","city_name_en":"Jahina Al Gharbia"},
            {"id":"393","province_id":"27","city_name_ar":"ساقلته","city_name_en":"Saqilatuh"},
            {"id":"394","province_id":"27","city_name_ar":"طما","city_name_en":"Tama"},
            {"id":"395","province_id":"27","city_name_ar":"طهطا","city_name_en":"Tahta"},
            {"id":"396","province_id":"27","city_name_ar":"الكوثر","city_name_en":"Alkawthar"}]';

        DB::table('cities')->insert(json_decode($cities, true));
    }
}
